language: cpp
os: linux
sudo: false
dist: trusty
branches:
  only:
  - master
env:
  global:
  - DEVKITPRO=/opt/devkitpro
  - WUT_ROOT=/opt/devkitpro/wut
  - DEVKITPPC=/opt/devkitpro/devkitPPC
  - PORTLIBREPOS=$HOME/portlibrepos
cache:
  directories:
  - "$HOME/.local"
  - "$DEVKITPRO"
addons:
  apt:
    packages:
    - p7zip-full
before_install:
- mkdir -p "${PORTLIBREPOS}"
- mkdir -p "${DEVKITPRO}"
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
  -O /tmp/devkitpro-pacman.deb; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg -i /tmp/devkitpro-pacman.deb;
  fi
- yes | sudo dkp-pacman -Syu devkitPPC --needed
- yes | sudo dkp-pacman -Syu general-tools --needed
- wget https://github.com/decaf-emu/wut/releases/download/1.0.0-beta2/wut.linux64.7z
install:
- 7z x -y $(ls | grep "linux") -o${WUT_ROOT}
- cd $PORTLIBREPOS
- git clone https://github.com/Maschell/WiiUPluginSystem.git
- git clone https://github.com/Maschell/libutils.git -b wut
- cd WiiUPluginSystem
- make && make install
- cd $PORTLIBREPOS
- cd libutils
- mkdir build && cd build
- cmake -DCMAKE_TOOLCHAIN_FILE=$WUT_ROOT/share/wut.toolchain.cmake -DCMAKE_INSTALL_PREFIX=$WUT_ROOT
  ../
- make install
- cd $PORTLIBREPOS
before_script:
- cd $TRAVIS_BUILD_DIR/
script:
- make -j8
before_deploy:
- cd $TRAVIS_BUILD_DIR/
- mkdir -p "wiiu/plugins"
- commit="$(git rev-parse --short=7 HEAD)"
- find -type f -name "*.mod" | xargs -i cp {} wiiu/plugins
- zip -r screenstreamer_wups_nightly_$commit.zip wiiu
- git config --local user.name "Maschell"
- git config --local user.email "Maschell@gmx.de"
- git tag "ScreenStreamerWUPS-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: H3sXW8voP9WWwK9PpSD1BXTFmNwss3z6FjX9UVZUOEga7Yu4Na4yUvDtmpEKOxLvFDjAOkS6tyB1UM0Ft9GNi1Qd2cPpSgsJZx5NiYDkiSc7A1UNEbYuMgS+deILnT3qNrTaXMjLeedyMZSTLTt2iThJVP31bwvOTs2nM08PuSrFO8sa0uuLpFyx9uCcznctZsRmSzaTbey/P2rSvTBSOtFHMkfTPLsBndSF1hEn/UUIoOguLUfuq/ovgTr1i6Bm+OMt35oLaaCnSs0JiglUYyXSHP53/14h4CVvQiq69EjHSSrsF46U60j3HA+05eJaxBnr1FZUWfHc/m245G4oSFjvKKCN0hXeRhcLQg1texz1TcI5PIzEgg50UAl6W1LdZVIksGSySojfH/P9FFUkRxtTzzDAgDz/UWNfnx9N9JEZbRsV0hp6goJSnHj/gpu2wxVdYSAVae3NTe7zYT5Le0l0vgpnVhcSVFaZQiy70xb26JPRa0msxFd3BXzYcGV/c+GsxVXoo0yTMpWae4CbWSonkCuNyPTdVQ05+TAP6KjJO9mEWRj+8XuFkRRUELiM7Oe5rHY0nIyQwECbF3yoQP3FDaw+WNhrs+d8ETbZ+uM9UcsCy9h9eGJCgbTU96mVylf9tXCUoVEEUBjXOYgs/joQy83hjCDCS96KVJNLI8g=
  file: screenstreamer_wups_nightly_$commit.zip
  on:
    repo: Maschell/StreamingPluginWiiU
